name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run:  |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run:  |
          python -m unittest discover -s src/test -v
  deployment:
      needs: tests
      runs-on: ubuntu-latest
      steps:
        - name: Fresh clone & repo install
          uses: appleboy/ssh-action@master
          with:
            #IP address of EC2 instance
            host: 54.166.131.95
            #User you created on the EC2 instance
            username: github-actions
            #Name of the secrets variable where you put your secret key
            key: ${{ secrets.SSH_KEY }}
            port: 22
            script: |
              sudo rm -rf Hangman-with-graphics
              git clone https://github.com/Magni0/Hangman-with-graphics.git
              python3.8 -m venv /home/github-actions/Hangman-with-graphics/venv
              /home/github-actions/Hangman-with-graphics/venv/bin/pip3.8 install -r /home/github-actions/Hangman-with-graphics/requirements.txt